### ISSUE TITLE
Upgrade 9.5 to 10.4  Wizard error 

### ISSUE THREAD

**Issue by hhaeb** [jweiland-net/weather2#21]
executing [weather2] Empty Logger of weather2 scheduler tasks leads to the following error:

Call to undefined method JWeiland\Weather2\Task\OpenWeatherMapTask::resetLogger()

It is impossible to finish the Upgrade Wizard

Screenshot of part back trace attached

<img width="851" alt="Anmerkung 2020-08-19 145106" src="https://user-images.githubusercontent.com/2345812/90636816-75708180-e22b-11ea-882d-46ca030d5c74.png">

**Comment by froemken** [comment]
Related to https://github.com/jweiland-net/weather2/issues/17

This is a really bad issue and I hope for a better scheduler implementation in TYPO3 in future.
If you have all data in mind or written down for your scheduler task somewhere I prefer to delete and create a new task.

Stefan

**Comment by pascal20997** [comment]
@hhaeb thanks for your report. The issue was an old snippet that I forgot to remove when updating the code of weather2 for TYPO3 v10. For TYPO3 v8 and v9 we added the method resetLogger to our own AbstractTask. This is no longer needed because AbstractTask::unsetScheduler() in v9 and v10 (recent versions) does unset the logger. I fixed that issue and will release 3.0.1 in a few minutes :)
