### ISSUE TITLE
Precipitation Field missing Value

### ISSUE THREAD

**Issue by LMFC-Krisi** [jweiland-net/weather2#37]
Hello
In the Weather Data the Field Precipitation (Niederschlag) shows every time 0.
Regards Michael

**Comment by froemken** [comment]
Hello @LMFC-Krisi 

can you test that again with current typo3_11_compatibility branch. I have found a lot of problems while upgrading. Maybe it is solved already.

Stefan

**Comment by LMFC-Krisi** [comment]
Hello Stefan
Thanks for your work.
Actually i have no test environment with Typo3_11, so i can't test it. Perhaps someone else can test it. 
If i have some time i will create a new Typo3_11 installation and test it.
Regards Michael

**Comment by LMFC-Krisi** [comment]
Hello Stefan
Today i test your typo3_11_compatibility branch with Typo 3  11.5.13  on my Website https://test.lmfc.de/allgemein/wetter
Now we need some precipitation to see if the Field has some Data. I hope tommorrow it will be rain in our Country. 
Regards Michael

**Comment by froemken** [comment]
Hello @LMFC-Krisi 

thank you for your support. Today I have added a test which checks for correct weather data. It also checks the value for "rain", if there is any in response:

https://github.com/jweiland-net/weather2/blob/typo3_11_compatibility/Tests/Functional/Task/OpenWeatherMapTaskTest.php#L189

Maybe the API has changed in the meanwhile, because in earlier versions the rain was just a simple array:

```
$rain = [
    0 => 5.3
]
```

Today the array shows the amount of rain for two time periods:

```
$rain = [
    '1h' => 5.3,
    '3h' => 12.4,
]
```

I have changed the code in typo3_11_compatibility accordingly, but, yes, I have the same problem: no rain here currently ;-)

Maybe you have time to check the current version of this branch again.

Have a nice start into the weekend

Stefan

**Comment by LMFC-Krisi** [comment]
Hallo Stefan
Gerne schaue ich mir deine Erneuerungen an sobald ich wieder einen Kopf dafür habe. Das wird aber eine Weile dauern. Meine Frau ist vor vier Wochen verstorben und deshalb habe ich im Moment keinen Kopf für solche Dinge. Ich bleibe aber am Ball. 
LG Michael

**Comment by froemken** [comment]
Hallo @LMFC-Krisi 

klaro, wir können uns hier auch gerne in Deutsch unterhalten. Für mich ist wichtig, dass das Problem gelöst wird ;-)
Ich wünsche Dir viel Stärke und echt gute Freunde in Deinem Umfeld, die den Schmerz mit Dir teilen. Nimm Dir die Zeit, die Du brauchst und ich freu mich einfach wieder was von Dir zu hören.

Schönen Start in die neue Woche

Stefan

**Comment by sfroemkenjw** [comment]
Hallo @LMFC-Krisi 

da ist bereits ne 11 kompatible Fassung ins TER hochgeladen habe und ich mich noch wage daran erinner, dass ich den Fehler behoben habe, schließe ich das Ticket hier.

Stefan
