### ISSUE TITLE
Uncaught TYPO3 Exception Argument

### ISSUE THREAD

**Issue by hhaeb** [jweiland-net/weather2#43]
After Upgrade of Typo3 to 10.4.3x the call  openweathermap.org api runs into error:
 
Uncaught TYPO3 Exception Argument 1 passed to TYPO3\CMS\Extbase\DomainObject\AbstractDomainObject::setPid() must be of the type int, string given, called in /home/XXXX/www/typo3conf/ext/weather2/Classes/Task/OpenWeatherMapTask.php on line 237

thrown in file /home/XXXX/typo3_src-10.4.36/typo3/sysext/extbase/Classes/DomainObject/AbstractDomainObject.php
in line 87

**Comment by sfroemkenjw** [comment]
Hello @hhaeb 

I remember that issue. It's not because of TYPO3 upgrade. It's because of weather2 upgrade from version 3 to 4. I have just release version 4.0.4 where I have added some upgrade instructions:

https://docs.typo3.org/p/jweiland/weather2/4.0/en-us/AdministratorManual/Upgrade/Index.html#update-from-3-x-to-4-0-0

Please remove that task and create it again.

Stefan
